In [1]:
import pandas as pd
import os
from rename_fa_to_en import rename_to_en
from codal_api import get_info
from convert_to_en import bs_to_en, cf_to_en, is_to_en
from num2words import num2words
from word2number import w2n

In [2]:
symbols = ['فاراک', 'شپدیس', 'شتران', 'شپنا', 'شستا']

In [3]:
# for symbol in symbols:
#     # get_info(symbols)
#     rename_to_en(symbol)

In [4]:
symbol = symbols[0]
symbol

'فاراک'

In [ ]:
dst_dir = os.path.join('E:/Projects/stock_unlock/csv_files', symbol)

In [19]:
#!/usr/bin/env python
import glob
import os
for i in symbols:
    dst_dir = os.path.join('E:/Projects/stock_unlock/csv_files', symbol)
    for j in ['balance_sheet', 'cash_flow', 'income_statement']:
        directory=os.path.join(dst_dir, j)
        os.chdir(directory)
        files=glob.glob('*.csv')
        for filename in files:
            os.remove(filename)
            # print(filename)

SyntaxError: invalid syntax (<ipython-input-19-8c2414abd90c>, line 5)

In [18]:
directory

'E:/Projects/stock_unlock/csv_files\\فاراک\\balance_sheet'

In [5]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [6]:
dst_dir = os.path.join('E:/Projects/stock_unlock/csv_files', symbol)
file_dir = f"C:/Users/new user/Downloads/{symbol}"
if not os.path.isdir(dst_dir):
    os.makedirs(dst_dir)
dirs = os.listdir(file_dir)

for file in dirs:
    if file[-14:] == 'notAudited.xls':
        if (file.replace('notAudited', 'Audited') in dirs) or (file.replace('notAudited', 'notAudited_modified') in dirs):
            continue
    if file[-23:] == 'notAudited_modified.xls' and file.replace('notAudited_modified', 'Audited') in dirs:
        continue

    try:
        data = pd.read_html(f'{file_dir}/{file}')
        for df in data:
            if 'جمع دارایی‌های جاری' in df.values or 'جمع دارايي‌هاي جاري' in df.values:
                # df.to_csv(f'{dst_dir}/{file}_bs.csv',index=False)
                pass
            elif 'نقد حاصل از عملیات' in df.values or 'نقد حاصل از عمليات' in df.values or 'جریان­‌های نقدی حاصل از فعالیت‌های تامین مالی' in df.values:
                # df.to_csv(f'{dst_dir}/{file}_cf.csv',index=False)
                pass
            elif 'سود (زیان) پایه هر سهم' in df.values or 'سود (زيان) پايه هر سهم' in df.values or 'درآمد سود سهام' in df.values:
                df.to_csv(f'{dst_dir}/{file}_is.csv',index=False)
                # pass
                # print(file)
            # else:
            #     print(df)
    except:
        print(file, '************')
        pass
    # print(file)

1398-12-29_Q4_Audited_Integrated.xls
1398-12-29_Q4_notAudited.xls
1398-6-31_Q2_Audited.xls
1398-6-31_Q2_Audited.xls ************
1398-6-31_Q2_Audited_modified_Integrated.xls
1398-6-31_Q2_Audited_modified_Integrated.xls ************
1398-6-31_Q2_notAudited.xls
1398-9-30_Q3_notAudited.xls
1398-9-30_Q3_notAudited.xls ************
1399-12-30_Q4_Audited_Integrated.xls
1399-12-30_Q4_notAudited.xls
1399-12-30_Q4_notAudited_Integrated.xls
1399-3-31_Q1_notAudited.xls
1399-6-31_Q2_Audited_Integrated.xls
1399-6-31_Q2_notAudited.xls
1399-6-31_Q2_notAudited_Integrated.xls
1399-9-30_Q3_notAudited.xls
1400-12-29_Q4_Audited_Integrated.xls
1400-12-29_Q4_notAudited.xls
1400-3-31_Q1_notAudited.xls
1400-3-31_Q1_notAudited_modified.xls
1400-6-31_Q2_Audited_Integrated.xls
1400-6-31_Q2_Audited_modified_Integrated.xls
1400-6-31_Q2_notAudited.xls
1400-6-31_Q2_notAudited_Integrated.xls
1400-9-30_Q3_notAudited.xls
1401-12-29_Q4_Audited_Integrated.xls
1401-12-29_Q4_notAudited.xls
1401-3-31_Q1_notAudited.xls
1401-6-31_Q2_Audited_Integrated.xls
1401-6-31_Q2_Audited_modified_Integrated.xls
1401-6-31_Q2_notAudited.xls
1401-6-31_Q2_notAudited_Integrated.xls
1401-9-30_Q3_notAudited.xls
1402-3-31_Q1_notAudited.xls

In [14]:
bs_dir = f'E:/Projects/stock_unlock/csv_files/{symbol}'
bs_path = os.path.join(bs_dir,'balance_sheet')
cf_path = os.path.join(bs_dir,'cash_flow')
is_path = os.path.join(bs_dir,'income_statement')
if not os.path.isdir(bs_path):
    os.mkdir(bs_path)
if not os.path.isdir(cf_path):
    os.mkdir(cf_path)
if not os.path.isdir(is_path):
    os.mkdir(is_path)
dirs = os.listdir(bs_dir)
for file in dirs:
    if '.csv' not in file:
        continue
    data = pd.read_csv(f'{bs_dir}/{file}')
    if type(data.columns) == tuple:
        col_names = []
        [col_names.append(data.columns[i][0]) for i in range(len(data.columns))]
        data.columns = col_names
        
    if True not in ['/' in data.columns[i] for i in range(len(data.columns))]:
        data.columns = data.loc[0]
        data.rename(columns={data.columns[0]:'شرح'},inplace=True)
        
    data.drop(0,axis=0,inplace=True)
    data.reset_index(drop=True, inplace=True)
    if file[-6:]=='bs.csv':
        if len(data.columns)>5:
            try:
                if 'درصد  تغییرات' in data.columns:
                    data1 = data.loc[0:,'شرح':'درصد  تغییرات']
                elif 'درصد تغییرات' in data.columns:
                    data1 = data.loc[0:,'شرح':'درصد تغییرات']
                data1 = data1[data1['شرح'].notna()]
                data2 = data.loc[0:,'شرح.1':]
                data2.columns = data1.columns
                x = pd.concat([data1, data2]).reset_index(drop=True)
                bs_to_en(x).to_csv(f"{bs_dir}/balance_sheet/{file[:-11]}.csv", index=False)
                os.remove(f'{bs_dir}/{file}')
            except:
                print(file, '**************')
                pass
        else:
            try:
                bs_to_en(data).to_csv(f"{bs_dir}/balance_sheet/{file[:-11]}.csv", index=False)
                os.remove(f'{bs_dir}/{file}')
            except:
                print(file)
                pass
    elif file[-6:]=='cf.csv':
        try:
            cf_to_en(data).to_csv(f"{bs_dir}/cash_flow/{file[:-11]}.csv", index=False)
            os.remove(f'{bs_dir}/{file}')
        except:
            print(file)
            pass
    elif file[-6:]=='is.csv':
        try:
            is_to_en(data).to_csv(f"{bs_dir}/income_statement/{file[:-11]}.csv", index=False)
            os.remove(f'{bs_dir}/{file}')
        except:
            print(file)
            pass
    # break

In [13]:
data

,شرح,دوره منتهی به ۱۳۹۸/۱۲/۲۹ جهت ارائه به حسابرس,تجدید ارائه شده دوره منتهی به ۱۳۹۷/۱۲/۲۹,تجدید ارائه شده دوره منتهی به ۱۳۹۸/۰۶/۳۱,درصد تغییر
0,عملیات در حال تداوم:,NaN,NaN,NaN,NaN
1,درآمدهای عملیاتی,"۲,۰۳۸,۵۴۸","۱,۲۰۶,۵۹۰","۳,۰۹۲,۲۵۲",۶۹
2,بهاى تمام شده درآمدهای عملیاتی,"(۱,۶۴۳,۰۱۰)","(۱,۰۸۵,۱۶۴)","(۲,۶۹۵,۰۴۹)",(۵۱)
3,سود (زيان) ناخالص,"۳۹۵,۵۳۸","۱۲۱,۴۲۶","۳۹۷,۲۰۳",۲۲۶
4,هزينه‏‌هاى فروش، ادارى و عمومى,"(۱۹۱,۰۸۷)","(۲۲۳,۷۵۲)","(۳۸۸,۷۹۸)",۱۵
5,هزینه کاهش ارزش دریافتنی‌‏ها (هزینه استثنایی),۰,۰,۰,NaN
6,ساير درآمدها,"۷۳,۲۴۰","۲۶,۷۴۳","۱۸۲,۷۵۵",۱۷۴
7,سایر هزینه‌ها,"(۲۵,۶۸۵)","(۲۴,۴۹۱)","(۴۲,۸۸۸)",(۵)
8,سود (زيان) عملياتي,"۲۵۲,۰۰۶","(۱۰۰,۰۷۴)","۱۴۸,۲۷۲",--
9,هزينه‏‌هاى مالى,"(۸۲,۹۶۰)","(۹۳,۶۱۱)","(۱۷۴,۹۳۷)",۱۱
10,سایر درآمدها و هزینه‌های غیرعملیاتی- درآمد سرم...,"۵,۵۰۳","۵,۶۲۲","۳۸,۲۴۵",(۲)
11,سایر درآمدها و هزینه‌های غیرعملیاتی- اقلام متفرقه,"(۵,۱۰۹)","۳۳۶,۷۵۱","۲۹۰,۳۹۸",--
12,سود (زيان) عمليات در حال تداوم قبل از ماليات,"۱۶۹,۴۴۰","۱۴۸,۶۸۸","۳۰۱,۹۷۸",۱۴
13,هزینه مالیات بر درآمد:,NaN,NaN,NaN,NaN
14,سال جاری,۰,۰,۰,NaN
15,سال‌های قبل,۰,۰,۰,NaN
16,سود (زيان) خالص عمليات در حال تداوم,"۱۶۹,۴۴۰","۱۴۸,۶۸۸","۳۰۱,۹۷۸",۱۴
17,عملیات متوقف شده:,NaN,NaN,NaN,NaN
18,سود (زیان) خالص عملیات متوقف شده,۰,۰,۰,NaN
19,سود (زيان) خالص,"۱۶۹,۴۴۰","۱۴۸,۶۸۸","۳۰۱,۹۷۸",۱۴
20,سود (زيان) پايه هر سهم,NaN,NaN,NaN,NaN
21,عملیاتی (ریال),۴۰,(۱۶),۲۴,--
22,غیرعملیاتی (ریال),(۱۳),۴۰,۲۴,--
23,ناشی از عملیات در حال تداوم,۲۷,۲۴,۴۸,۱۳
24,ناشی از عملیات متوقف شده,۰,۰,۰,NaN
25,سود (زيان) پايه هر سهم,۲۷,۲۴,۴۸,۱۳
26,سود (زیان) خالص هر سهم– ریال,۲۷,۲۴,۴۸,۱۳
27,سرمایه,"۶,۲۸۶,۵۴۷","۶,۲۸۶,۵۴۷","۶,۲۸۶,۵۴۷",NaN
28,NaN,NaN,NaN,NaN,NaN

In [17]:
data1 = data.loc[0:,'شرح':'درصد  تغییرات']

In [18]:
data1

,شرح,واقعی دوره منتهی به ۱۴۰۲/۰۶/۳۱,واقعی دوره منتهی به ۱۴۰۱/۰۶/۳۱,درصد تغییرات
1,Operating revenues,0,0,0
2,Dividend income,0,0,0
3,Guaranteed profit income,0,0,0
4,Gain (loss) from sale of investments,0,0,0
5,Gain (loss) from change in fair value of secur...,0,2600055,--
6,Other operating income,0,0,0
7,Total operating revenues,0,0,0
8,Operating expenses,0,2600055,--
9,"Selling, general, and administrative expenses",0,0,0
10,Other operating expenses,-246641,-158962,۵۵
11,Total operating expenses,0,0,0
12,Operating profit (loss),-246641,-158962,۵۵
13,Financial expenses,-246641,2441093,--
14,Other non-operating income and expenses,-3953357,-2264496,۷۵
15,Continuing operations profit (loss) before tax,67822,42620,۵۹
16,Income tax,-4132176,219217,--
17,Net income (loss) from continuing operations,0,0,0
18,Discontinued operations profit (loss) after tax,-4132176,219217,--
19,Net profit (loss),0,0,0
20,Earnings (loss) per share,-4132176,219217,--
21,Basic earnings (loss) per share from continuin...,0,0,0
22,Basic earnings (loss) per share from continuin...,0,0,0
23,Basic earnings (loss) per share from discontin...,-3,0,--
24,Earnings (loss) per share,0,0,0
25,Diluted earnings (loss) per share,-3,0,--
26,Diluted earnings (loss) per share from continu...,0,0,0
27,Diluted earnings (loss) per share from continu...,0,0,0
28,Diluted earnings (loss) per share from discont...,-3,0,--
29,Diluted earnings (loss) per share,0,0,0
30,Accumulated retained earnings,-3,0,--
31,Net profit (loss),0,0,0
32,Beginning retained earnings,-4132176,219217,--
33,Periodic adjustments,342522984,253693287,۳۵
34,Adjusted beginning retained earnings,0,0,0
35,Approved dividend,342522984,253693287,۳۵
36,Capital changes from retained earnings,0,0,0
37,Unappropriated retained earnings at the beginn...,0,0,0
38,Transfer from other equity items,342522984,253693287,۳۵
39,Retained earnings available for allocation,0,0,0
40,Transfer to legal reserves,338390808,253912504,۳۳
41,Transfer to other reserves,0,-10961,--
42,Retained earnings at the end of the period,0,-2600055,--
43,Net earnings (loss) per share - Iranian rials,338390808,251301488,۳۵
44,Capital,-3,0,--
45,سرمایه,1636013456,1636013456,۰
46,0,0,0,0

In [1]:
import pandas as pd

In [2]:
data = pd.read_html('c:/Users/new user/Downloads/فاراک/1401-12-29_Q4_notAudited.xls')[0]

In [3]:
col = []

In [4]:
[col.append(data.columns[i][0]) for i in range(len(data.columns))]

[None, None, None, None, None]

In [5]:
data.columns = col

In [6]:
from convert_to_en import is_to_en

In [7]:
is_to_en(data)

,Description,2023-3-20,2022-3-20,2022-9-22
0,Continuing operations,0,0,0
1,Operating revenues,11042880,9838649,18924990
2,Cost of goods sold for operating income,-9349341,-8239930,-15682497
3,Gross profit (loss),1693539,1598719,3242493
4,"Selling, general, and administrative expenses",-885040,-569896,-1312873
5,Impairment of receivables (extraordinary expense),0,0,0
6,Other incomes,1224538,115874,205017
7,Other expenses,-64270,-43615,-120218
8,Operating profit (loss),1968767,1101082,2014419
9,Financial expenses,-263017,-218819,-427932
10,Other non-operating income and expenses,32933,70785,92488
11,Other non-operating income - Miscellaneous items,154206,381101,443202
12,Continuing operations profit (loss) before tax,1892889,1334149,2122177
13,Income tax,0,0,0
14,Current year,-214731,-202138,-287631
15,Prior years,0,-23000,-23000
16,Net income (loss) from continuing operations,1678158,1109011,1811546
17,Discontinued operations,0,0,0
18,Net profit (loss) from discontinued operations,0,0,0
19,Net profit (loss),1678158,1109011,1811546
20,Earnings (loss) per share,0,0,0
21,(Operational in Rials),95,43,89
22,(Non-operational in Rials),-14,10,5
23,Attributable to continuing operations,81,53,94
24,Attributable to discontinued operations,0,0,0
25,Earnings (loss) per share,81,53,94
26,Net earnings (loss) per share - Iranian rials,81,54,88
27,Capital,20637727,20637727,20637727
28,0,0,0,0

In [20]:
data[19].to_csv('djfkl.csv')

In [21]:
if 'سود (زیان) پایه هر سهم' in data[19].values:
    print('hellllo')

hellllo

In [22]:
df = pd.read_csv('E:/Projects/stock_unlock/csv_files/شستا/1402-3-31_Q1_Audited.xls_bs.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'E:/Projects/stock_unlock/csv_files/شستا/1402-3-31_Q1_Audited.xls_bs.csv'

In [ ]:
data[0].columns.values

array(['شرح', 'پایان عملکرد واقعی منتهی به۱۳۹۹/۰۹/۳۰',
       'پایان سال مالی قبل۱۳۹۹/۰۳/۳۱', 'درصد تغییرات', 'شرح.1',
       'پایان عملکرد واقعی منتهی به۱۳۹۹/۰۹/۳۰.1',
       'پایان سال مالی قبل۱۳۹۹/۰۳/۳۱.1', 'درصد تغییرات.1'], dtype=object)

In [ ]:
if True in ['/' in data[0].columns[i] for i in range(len(data[0].columns))]:
    print('hellos')

hellos

In [ ]:
if True not in ['/' in df.columns[i] for i in range(len(df.columns))]:
    df.columns = df.loc[0]

In [ ]:
df

,شرح,۱۴۰۲/۰۳/۳۱,۱۴۰۱/۰۳/۳۱,درصد تغییرات,شرح.1,۱۴۰۲/۰۳/۳۱.1,۱۴۰۱/۰۳/۳۱.1,درصد تغییرات.1
0,شرح,۱۴۰۲/۰۳/۳۱,۱۴۰۱/۰۳/۳۱,درصد تغییرات,شرح.1,۱۴۰۲/۰۳/۳۱.1,۱۴۰۱/۰۳/۳۱.1,درصد تغییرات.1
1,دارایی‌‌ها,NaN,NaN,NaN,بدهی‌ها و حقوق صاحبان سهام,NaN,NaN,NaN
2,دارایی‌‌های جاری,NaN,NaN,NaN,بدهی‌های جاری,NaN,NaN,NaN
3,موجودی نقد,"۱۷,۲۵۵,۸۳۸","۸۷۲,۷۲۷","۱,۸۷۷",پرداختنی‌های تجاری,۰,۴۸۹,--
4,سرمایه‌گذاری‌‌های کوتاه‌مدت,"۴۴۸,۴۵۲","۶۶۶,۰۹۲",(۳۳),پرداختنی‌های غیرتجاری,"۱۷,۷۱۰,۲۰۱","۱,۴۵۸,۲۰۹","۱,۱۱۵"
5,دریافتنی‌‌های تجاری,"۳۶۲,۲۴۱,۴۸۹","۲۵۳,۵۹۹,۶۶۲",۴۳,مالیات پرداختنی,"۱۴,۴۲۵","۱۸,۸۹۵",(۲۴)
6,دریافتنی‌‌های غیرتجاری,"۱,۶۸۳,۳۱۴","۱,۵۵۸,۱۹۱",۸,سود سهام پرداختنی,"۳,۲۷۶,۱۹۴","۱,۰۸۶,۸۶۲",۲۰۱
7,پیش پرداخت‌ها و سفارشات,"۲,۳۹۸,۲۹۱","۶,۹۶۶","۳۴,۳۲۹",تسهیلات مالی,"۳۴,۹۵۶,۳۸۱","۲۴,۶۵۱,۱۳۵",۴۲
8,دارایی‌های نگهداری شده برای فروش,۰,۰,NaN,ذخایر,۰,۰,NaN
9,جمع دارایی‌های جاری,"۳۸۴,۰۲۷,۳۸۴","۲۵۶,۷۰۳,۶۳۸",۵۰,پیش‌دریافت‌های جاری,۰,۰,NaN
10,دارایی‌‌های غیرجاری,NaN,NaN,NaN,بدهی‌های مرتبط با دارایی‌های نگهداری شده برای ...,۰,۰,NaN
11,دریافتنی‌‌های بلندمدت,"۹۸,۲۷۲","۶۷,۰۰۱",۴۷,جمع بدهی‌های جاری,"۵۵,۹۵۷,۲۰۱","۲۷,۲۱۵,۵۹۰",۱۰۶
12,سرمایه‌گذاری‌های بلندمدت,"۱,۸۴۷,۸۲۶,۸۹۲","۱,۷۹۴,۲۴۵,۷۱۹",۳,بدهی‌های غیرجاری,NaN,NaN,NaN
13,سرمایه‌گذاری در املاک,۰,۰,NaN,پرداختنی‌های بلندمدت,۰,۰,NaN
14,دارایی‌های نامشهود,۵۲۷,۵۲۷,۰,پیش‌دریافت‌های غیرجاری,۰,۰,NaN
15,دارایی‌های ثابت مشهود,"۲,۳۴۶,۹۷۹","۲,۳۰۰,۲۵۰",۲,تسهیلات مالی بلندمدت,"۷۰,۰۰۰,۰۰۰","۳۰,۰۰۰,۰۰۰",۱۳۳
16,سایر دارایی‌ها,۰,۰,NaN,ذخیره مزایای پایان خدمت کارکنان,"۲۳۷,۸۴۱","۱۵۹,۰۸۵",۵۰
17,جمع دارایی‌های غیرجاری,"۱,۸۵۰,۲۷۲,۶۷۰","۱,۷۹۶,۶۱۳,۴۹۷",۳,جمع بدهی‌های غیرجاری,"۷۰,۲۳۷,۸۴۱","۳۰,۱۵۹,۰۸۵",۱۳۳
18,NaN,NaN,NaN,NaN,جمع بدهی‌ها,"۱۲۶,۱۹۵,۰۴۲","۵۷,۳۷۴,۶۷۵",۱۲۰
19,NaN,NaN,NaN,NaN,حقوق صاحبان سهام,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,سرمایه,"۱,۶۳۶,۰۱۳,۴۵۶","۱,۶۳۶,۰۱۳,۴۵۶",۰
21,NaN,NaN,NaN,NaN,افزایش (کاهش) سرمایه در جریان,۰,۰,NaN
22,NaN,NaN,NaN,NaN,صرف (کسر) سهام,"۱,۲۶۰,۶۶۶","۱۹,۲۰۴","۶,۴۶۵"
23,NaN,NaN,NaN,NaN,سهام خزانه,"(۱۱,۶۰۸,۶۰۹)","(۱۴,۶۶۳,۵۴۹)",(۲۱)
24,NaN,NaN,NaN,NaN,اندوخته قانونی,"۴۱,۲۷۶,۷۵۶","۲۴,۸۴۰,۳۵۸",۶۶
25,NaN,NaN,NaN,NaN,سایر اندوخته‌ها,"۹۸,۶۳۹,۷۵۹","۹۶,۰۳۹,۷۰۴",۳
26,NaN,NaN,NaN,NaN,مازاد تجدید ارزیابی دارایی‌های غیرجاری نگهداری...,۰,۰,NaN
27,NaN,NaN,NaN,NaN,مازاد تجدید ارزیابی دارایی‌ها,۰,۰,NaN
28,NaN,NaN,NaN,NaN,تفاوت تسعیر ناشی از تبدیل به واحد پول گزارشگری,۰,۰,NaN
29,NaN,NaN,NaN,NaN,اندوخته تسعير ارز دارايي‌ها و بدهي‌هاي شرکت‌ها...,۰,۰,NaN
30,NaN,NaN,NaN,NaN,سود (زیان) انباشته,"۳۴۲,۵۲۲,۹۸۴","۲۵۳,۶۹۳,۲۸۷",۳۵
31,NaN,NaN,NaN,NaN,جمع حقوق صاحبان سهام,"۲,۱۰۸,۱۰۵,۰۱۲","۱,۹۹۵,۹۴۲,۴۶۰",۶
32,جمع دارایی‌ها,"۲,۲۳۴,۳۰۰,۰۵۴","۲,۰۵۳,۳۱۷,۱۳۵",۹,جمع بدهی‌ها و حقوق صاحبان سهام,"۲,۲۳۴,۳۰۰,۰۵۴","۲,۰۵۳,۳۱۷,۱۳۵",۹

In [ ]:
data = data.fillna(0)

In [ ]:
x = data[data.columns[1]].map(lambda x:(str(x).replace(',','').replace(')','').replace('(','-')))

In [ ]:
w2n.word_to_num(num2words(x[12]).replace(',',''))

-24443

In [ ]:
x = x.drop(0)

In [ ]:
x.map(lambda i:w2n.word_to_num(num2words(i).replace(',','')))

1            0
2      1284528
3       -58464
4      1226064
5            0
6         2785
7      -767373
8            0
9            0
10           0
11           0
12      -24443
13           0
14           0
15       45000
16           0
17           0
18           0
19           0
20           0
21      145038
22     -598993
23      627071
24           0
25           0
26           0
27           0
28           0
29           0
30           0
31           0
32           0
33           0
34           0
35           0
36           0
37           0
38           0
39           0
40     -493644
41     -493644
42      133427
43     9113349
44     1119491
45    10366267
46           0
Name: دوره منتهي به ۱۴۰۱/۰۶/۳۱, dtype: int64

In [ ]:
x

0     حسابرسی شده
1               0
2         ۱۲۸۴۵۲۸
3          -۵۸۴۶۴
4         ۱۲۲۶۰۶۴
5               0
6            ۲۷۸۵
7         -۷۶۷۳۷۳
8               ۰
9               ۰
10              ۰
11              ۰
12         -۲۴۴۴۳
13              ۰
14              ۰
15          ۴۵۰۰۰
16              ۰
17              ۰
18              ۰
19              ۰
20              ۰
21         ۱۴۵۰۳۸
22        -۵۹۸۹۹۳
23         ۶۲۷۰۷۱
24              0
25              ۰
26              ۰
27              ۰
28              ۰
29              ۰
30              ۰
31              ۰
32              ۰
33              ۰
34              ۰
35              ۰
36              ۰
37              ۰
38              ۰
39              ۰
40        -۴۹۳۶۴۴
41        -۴۹۳۶۴۴
42         ۱۳۳۴۲۷
43        ۹۱۱۳۳۴۹
44        ۱۱۱۹۴۹۱
45       ۱۰۳۶۶۲۶۷
46              ۰
Name: دوره منتهي به ۱۴۰۱/۰۶/۳۱, dtype: object

In [ ]:
for i in range(len(x)):
    print(w2n.word_to_num(num2words(x[i+1]).replace(',','')))

0
1284528
-58464
1226064
0
2785
-767373
0
0
0
0
-24443
0
0
45000
0
0
0
0
0
145038
-598993
627071
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
-493644
-493644
133427
9113349
1119491
10366267
0

KeyError: 47

In [ ]:
data[data.columns[1]].map(lambda x: w2n.word_to_num(num2words(str(x).replace(',','')).replace(',','')))

InvalidOperation: [<class 'decimal.ConversionSyntax'>]

In [ ]:
data = pd.read_csv('E:/Projects/stock_unlock/csv_files/1397-12-29_Q4_Audited.xls_bs.csv')

In [ ]:
data.columns

Index(['شرح', 'پایان عملکرد واقعی منتهی به۱۳۹۷/۱۲/۲۹',
       'پایان سال مالی قبل۱۳۹۶/۱۲/۲۹', 'درصد تغییرات', 'شرح.1',
       'پایان عملکرد واقعی منتهی به۱۳۹۷/۱۲/۲۹.1',
       'پایان سال مالی قبل۱۳۹۶/۱۲/۲۹.1', 'درصد تغییرات.1'],
      dtype='object')

In [ ]:
data1 = data.loc[0:,'شرح':'درصد تغییرات']
data1 = data1[data1['شرح'].notna()]
data2 = data.loc[0:,'شرح.1':]
data2.columns = data1.columns
x = pd.concat([data1, data2]).reset_index(drop=True)
y = convert_to_en(x)

In [ ]:
data1 = data1[data1['شرح'].notna()]

In [ ]:
data2 = data.loc[0:,'شرح.1':]

In [ ]:
data2

,شرح.1,پایان عملکرد واقعی منتهی به۱۳۹۷/۱۲/۲۹.1,پایان سال مالی قبل۱۳۹۶/۱۲/۲۹.1,درصد تغییرات.1
0,بدهی‌ها و حقوق صاحبان سهام,NaN,NaN,NaN
1,بدهی‌های جاری,NaN,NaN,NaN
2,پرداختنی‌های تجاری,"۱,۱۰۶,۴۶۲","۷۴۴,۶۵۲",۴۹
3,پرداختنی‌های غیرتجاری,"۴۳۱,۴۳۶","۵۰۴,۱۵۱",(۱۴)
4,مالیات پرداختنی,"۱۱۰,۶۱۰","۴۰,۱۲۶",۱۷۶
5,سود سهام پرداختنی,۰,"۱۹,۰۷۵",--
6,تسهیلات مالی,"۱۳۵,۸۰۱","۳۲۷,۲۳۱",(۵۸)
7,ذخایر,"۱۴۶,۳۵۱","۱۶۰,۵۵۶",(۹)
8,پیش‌دریافت‌های جاری,"۴,۷۲۷,۳۷۲","۲,۴۶۶,۰۳۳",۹۲
9,بدهی‌های مرتبط با دارایی‌های نگهداری شده برای ...,۰,۰,--
10,جمع بدهی‌های جاری,"۶,۶۵۸,۰۳۲","۴,۲۶۱,۸۲۴",۵۶
11,بدهی‌های غیرجاری,NaN,NaN,NaN
12,پرداختنی‌های بلندمدت,"۲۶۵,۴۰۵","۲۰۱,۷۷۷",۳۲
13,پیش‌دریافت‌های غیرجاری,۰,۰,--
14,تسهیلات مالی بلندمدت,۰,۰,--
15,ذخیره مزایای پایان خدمت کارکنان,"۱۱۰,۸۱۳","۷۲,۶۲۲",۵۳
16,جمع بدهی‌های غیرجاری,"۳۷۶,۲۱۸","۲۷۴,۳۹۹",۳۷
17,جمع بدهی‌ها,"۷,۰۳۴,۲۵۰","۴,۵۳۶,۲۲۳",۵۵
18,حقوق صاحبان سهام,NaN,NaN,NaN
19,سرمایه,"۱,۰۰۰,۰۰۰","۷۴۰,۰۰۰",۳۵
20,افزایش (کاهش) سرمایه در جریان,۰,۰,--
21,صرف (کسر) سهام,۰,۰,--
22,سهام خزانه,۰,۰,--
23,اندوخته قانونی,"۱۰۰,۰۰۰","۷۲,۸۲۶",۳۷
24,سایر اندوخته‌ها,۰,۰,--
25,مازاد تجدید ارزیابی دارایی‌های نگهداری شده برا...,۰,۰,--
26,مازاد تجدید ارزیابی دارایی‌ها,۰,۰,--
27,تفاوت تسعیر ناشی از تبدیل به واحد پول گزارشگری,"۳,۱۸۹,۰۸۲","۳۷۶,۷۶۹",۷۴۶
28,اندوخته تسعیر ارز دارایی‌ها و بدهی‌های شرکت‌ها...,۰,۰,--
29,سود (زیان) انباشته,"۶۱۳,۱۵۹","۴۸۶,۶۳۱",۲۶
30,جمع حقوق صاحبان سهام,"۴,۹۰۲,۲۴۱","۱,۶۷۶,۲۲۶",۱۹۲
31,جمع بدهی‌ها و حقوق صاحبان سهام,"۱۱,۹۳۶,۴۹۱","۶,۲۱۲,۴۴۹",۹۲

In [ ]:
data2.columns = data1.columns

In [ ]:
x = pd.concat([data1, data2]).reset_index(drop=True)

In [ ]:
y = convert_to_en(x)

In [ ]:
y

,Description,2019-3-20,2018-3-20,Percentage Change
1,Current Assets,0,0,0
2,Cash and Cash Equivalents,389473,77789,۴۰۱
3,Short-Term Investments,30000,75000,(۶۰)
4,Trade and Other Receivables,5145986,2710832,۹۰
5,No Trade Receivables,39407,49432,(۲۰)
6,Inventory,860581,213289,۳۰۳
7,Orders and Prepayments,231546,200037,۱۶
8,Assets Held for Sale,246975,101879,۱۴۲
9,Total Current Assets,6943968,3428258,۱۰۳
10,Non-Current Assets,0,0,0
11,Long-Term Receivables,3461134,1828955,۸۹
12,Long-Term Investments,339748,294965,۱۵
13,Investment in Properties,0,0,--
14,Intangible Assets,1263,1448,(۱۳)
15,Tangible Fixed Assets,1190378,658823,۸۱
16,Other Assets,0,0,--
17,Total Non-Current Assets,4992523,2784191,۷۹
18,Total Assets,11936491,6212449,۹۲
19,Equity and Liabilities,0,0,0
20,Current Liabilities,0,0,0
21,Trade and Other Payables,1106462,744652,۴۹
22,No Trade Payables,431436,504151,(۱۴)
23,Tax Payable,110610,40126,۱۷۶
24,Dividends Payable,0,19075,--
25,Short-Term Financial Facilities,135801,327231,(۵۸)
26,Provisions,146351,160556,(۹)
27,Advances Received,4727372,2466033,۹۲
28,Liabilities Related to Assets Held for Sale,0,0,--
29,Total Current Liabilities,6658032,4261824,۵۶
30,Non-Current Liabilities,0,0,0
31,Long-Term Payables,265405,201777,۳۲
32,Non-Current Advances Received,0,0,--
33,Long-Term Financial Facilities,0,0,--
34,Employees End of Service Benefits Provision,110813,72622,۵۳
35,Total Non-Current Liabilities,376218,274399,۳۷
36,Total Liabilities,7034250,4536223,۵۵
37,Equity,0,0,0
38,Capital,1000000,740000,۳۵
39,Capital Increase in Progress,0,0,--
40,Treasury Share,0,0,--
41,Treasury Shares,0,0,--
42,Legal Reserve,100000,72826,۳۷
43,Other Reserves,0,0,--
44,مازاد تجدید ارزیابی دارایی‌های نگهداری شده برا...,0,0,--
45,Revaluation Surplus,0,0,--
46,Foreign Operations Exchange Differences,3189082,376769,۷۴۶
47,اندوخته تسعیر ارز دارایی‌ها و بدهی‌های شرکت‌ها...,0,0,--
48,Retained Earnings (Loss),613159,486631,۲۶
49,Total Equity,4902241,1676226,۱۹۲
50,Total Equity and Liabilities,11936491,6212449,۹۲

In [ ]:
data

,شرح,پایان عملکرد واقعی منتهی به۱۳۹۷/۱۲/۲۹,پایان سال مالی قبل۱۳۹۶/۱۲/۲۹,درصد تغییرات,شرح.1,پایان عملکرد واقعی منتهی به۱۳۹۷/۱۲/۲۹.1,پایان سال مالی قبل۱۳۹۶/۱۲/۲۹.1,درصد تغییرات.1
0,دارایی‌‌ها,NaN,NaN,NaN,بدهی‌ها و حقوق صاحبان سهام,NaN,NaN,NaN
1,دارایی‌‌های جاری,NaN,NaN,NaN,بدهی‌های جاری,NaN,NaN,NaN
2,موجودی نقد,"۳۸۹,۴۷۳","۷۷,۷۸۹",۴۰۱,پرداختنی‌های تجاری,"۱,۱۰۶,۴۶۲","۷۴۴,۶۵۲",۴۹
3,سرمایه‌گذاری‌‌های کوتاه مدت,"۳۰,۰۰۰","۷۵,۰۰۰",(۶۰),پرداختنی‌های غیرتجاری,"۴۳۱,۴۳۶","۵۰۴,۱۵۱",(۱۴)
4,دریافتنی‌‌های تجاری,"۵,۱۴۵,۹۸۶","۲,۷۱۰,۸۳۲",۹۰,مالیات پرداختنی,"۱۱۰,۶۱۰","۴۰,۱۲۶",۱۷۶
5,دریافتنی‌‌های غیرتجاری,"۳۹,۴۰۷","۴۹,۴۳۲",(۲۰),سود سهام پرداختنی,۰,"۱۹,۰۷۵",--
6,موجودی مواد و کالا,"۸۶۰,۵۸۱","۲۱۳,۲۸۹",۳۰۳,تسهیلات مالی,"۱۳۵,۸۰۱","۳۲۷,۲۳۱",(۵۸)
7,پیش پرداخت‌ها و سفارشات,"۲۳۱,۵۴۶","۲۰۰,۰۳۷",۱۶,ذخایر,"۱۴۶,۳۵۱","۱۶۰,۵۵۶",(۹)
8,دارایی‌های نگهداری شده برای فروش,"۲۴۶,۹۷۵","۱۰۱,۸۷۹",۱۴۲,پیش‌دریافت‌های جاری,"۴,۷۲۷,۳۷۲","۲,۴۶۶,۰۳۳",۹۲
9,جمع دارایی‌های جاری,"۶,۹۴۳,۹۶۸","۳,۴۲۸,۲۵۸",۱۰۳,بدهی‌های مرتبط با دارایی‌های نگهداری شده برای ...,۰,۰,--
10,دارایی‌‌های غیرجاری,NaN,NaN,NaN,جمع بدهی‌های جاری,"۶,۶۵۸,۰۳۲","۴,۲۶۱,۸۲۴",۵۶
11,دریافتنی‌‌های بلندمدت,"۳,۴۶۱,۱۳۴","۱,۸۲۸,۹۵۵",۸۹,بدهی‌های غیرجاری,NaN,NaN,NaN
12,سرمایه‌گذاری‌های بلندمدت,"۳۳۹,۷۴۸","۲۹۴,۹۶۵",۱۵,پرداختنی‌های بلندمدت,"۲۶۵,۴۰۵","۲۰۱,۷۷۷",۳۲
13,سرمایه‌گذاری در املاک,۰,۰,--,پیش‌دریافت‌های غیرجاری,۰,۰,--
14,دارایی‌های نامشهود,"۱,۲۶۳","۱,۴۴۸",(۱۳),تسهیلات مالی بلندمدت,۰,۰,--
15,دارایی‌های ثابت مشهود,"۱,۱۹۰,۳۷۸","۶۵۸,۸۲۳",۸۱,ذخیره مزایای پایان خدمت کارکنان,"۱۱۰,۸۱۳","۷۲,۶۲۲",۵۳
16,سایر دارایی‌ها,۰,۰,--,جمع بدهی‌های غیرجاری,"۳۷۶,۲۱۸","۲۷۴,۳۹۹",۳۷
17,جمع دارایی‌های غیرجاری,"۴,۹۹۲,۵۲۳","۲,۷۸۴,۱۹۱",۷۹,جمع بدهی‌ها,"۷,۰۳۴,۲۵۰","۴,۵۳۶,۲۲۳",۵۵
18,NaN,NaN,NaN,NaN,حقوق صاحبان سهام,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,سرمایه,"۱,۰۰۰,۰۰۰","۷۴۰,۰۰۰",۳۵
20,NaN,NaN,NaN,NaN,افزایش (کاهش) سرمایه در جریان,۰,۰,--
21,NaN,NaN,NaN,NaN,صرف (کسر) سهام,۰,۰,--
22,NaN,NaN,NaN,NaN,سهام خزانه,۰,۰,--
23,NaN,NaN,NaN,NaN,اندوخته قانونی,"۱۰۰,۰۰۰","۷۲,۸۲۶",۳۷
24,NaN,NaN,NaN,NaN,سایر اندوخته‌ها,۰,۰,--
25,NaN,NaN,NaN,NaN,مازاد تجدید ارزیابی دارایی‌های نگهداری شده برا...,۰,۰,--
26,NaN,NaN,NaN,NaN,مازاد تجدید ارزیابی دارایی‌ها,۰,۰,--
27,NaN,NaN,NaN,NaN,تفاوت تسعیر ناشی از تبدیل به واحد پول گزارشگری,"۳,۱۸۹,۰۸۲","۳۷۶,۷۶۹",۷۴۶
28,NaN,NaN,NaN,NaN,اندوخته تسعیر ارز دارایی‌ها و بدهی‌های شرکت‌ها...,۰,۰,--
29,NaN,NaN,NaN,NaN,سود (زیان) انباشته,"۶۱۳,۱۵۹","۴۸۶,۶۳۱",۲۶
30,NaN,NaN,NaN,NaN,جمع حقوق صاحبان سهام,"۴,۹۰۲,۲۴۱","۱,۶۷۶,۲۲۶",۱۹۲
31,جمع دارایی‌ها,"۱۱,۹۳۶,۴۹۱","۶,۲۱۲,۴۴۹",۹۲,جمع بدهی‌ها و حقوق صاحبان سهام,"۱۱,۹۳۶,۴۹۱","۶,۲۱۲,۴۴۹",۹۲

In [ ]:
y['Description'][1]

'دارایی\u200c\u200cهای جاری'